// Generated by scripts/build-icons.mjs from icons/src/acts/check.mjs. Do not edit.
// The check glyph's tick on the 24 grid, in the order the pen draws it.
import CoreGraphics

enum MetalTickRoute {
    static let start = CGPoint(x: 5.4, y: 12.6)
    static let corner = CGPoint(x: 9.5, y: 16.7)
    static let tip = CGPoint(x: 18.6, y: 7.3)
}
