// Generated by scripts/build-icons.mjs from icons/src/icons.mjs. Do not edit.
// Each draws its own glyph only: importing one ships that glyph, not the catalog.
import { glyphIcon } from './Icon';
import * as glyphs from './glyphs.generated';

/** Select. Hover: The pointer draws back, clicks its tip down, and a ring opens where it lands.. Press: plays the same act. */
export const SelectIcon = /* @__PURE__ */ glyphIcon(glyphs.selectGlyph, "SelectIcon");
/** Text. Hover: The T is lifted, struck down onto its foot like a piece of type, and the caret appears after it.. Press: plays the same act. */
export const TextIcon = /* @__PURE__ */ glyphIcon(glyphs.textGlyph, "TextIcon");
/** Note. Hover: The corner peels open, the lines are written fresh, and the corner is pressed back down.. Press: plays the same act. */
export const NoteIcon = /* @__PURE__ */ glyphIcon(glyphs.noteGlyph, "NoteIcon");
/** Image. Hover: The sun dips behind the ridge, climbs into the sky with a flare of rays, and sets again.. Press: plays the same act. */
export const ImageIcon = /* @__PURE__ */ glyphIcon(glyphs.imageGlyph, "ImageIcon");
/** Link. Hover: The two links are pulled apart on their bar, then snap back into each other and a spark squeezes out at the join.. Press: plays the same act. */
export const LinkIcon = /* @__PURE__ */ glyphIcon(glyphs.linkGlyph, "LinkIcon");
/** Draw. Hover: The pencil lifts back, comes down on its point and pulls a stroke across the page, then goes back to its place.. Press: plays the same act. */
export const DrawIcon = /* @__PURE__ */ glyphIcon(glyphs.drawGlyph, "DrawIcon");
/** Pen. Hover: The nib writes a wave of ink, presses at the end of the line, and a drop of ink blooms and soaks in.. Press: plays the same act. */
export const PenIcon = /* @__PURE__ */ glyphIcon(glyphs.penGlyph, "PenIcon");
/** Marker. Hover: The marker plants its chisel flat and sweeps right, laying a see-through band as far as it goes.. Press: plays the same act. */
export const MarkerIcon = /* @__PURE__ */ glyphIcon(glyphs.markerGlyph, "MarkerIcon");
/** Line. Hover: The end handle is picked up and dragged back, the pen presses the start, and the line is drawn out to snap onto its end.. Press: plays the same act. */
export const LineIcon = /* @__PURE__ */ glyphIcon(glyphs.lineGlyph, "LineIcon");
/** Arrow. Hover: The arrow is drawn back from its held tail and thrust at its mark; the head strikes, compresses into its tip, and rebounds.. Press: plays the same act. */
export const ArrowIcon = /* @__PURE__ */ glyphIcon(glyphs.arrowGlyph, "ArrowIcon");
/** Rectangle. Hover: A handle grabs the far corner and drags the box in toward its pinned corner, then out past its size; let go, it springs back.. Press: plays the same act. */
export const RectangleIcon = /* @__PURE__ */ glyphIcon(glyphs.rectangleGlyph, "RectangleIcon");
/** Ellipse. Hover: A pen comes down on the ellipse and draws it again all the way round; the loop closes where it began.. Press: plays the same act. */
export const EllipseIcon = /* @__PURE__ */ glyphIcon(glyphs.ellipseGlyph, "EllipseIcon");
/** Eraser. Hover: The eraser is pressed onto a scribble and rubbed left, right and left; the scribble goes a pass at a time and crumbs flick away.. Press: plays the same act. */
export const EraserIcon = /* @__PURE__ */ glyphIcon(glyphs.eraserGlyph, "EraserIcon");
/** Layout. Hover: The panes are drawn apart, snap back onto the grid, and the gutter rule flashes where they seat.. Press: plays the same act. */
export const LayoutIcon = /* @__PURE__ */ glyphIcon(glyphs.layoutGlyph, "LayoutIcon");
/** Tidy. Hover: The loose pills are knocked square against the guide, and registration ticks flash where they sit flush.. Press: plays the same act. */
export const TidyIcon = /* @__PURE__ */ glyphIcon(glyphs.tidyGlyph, "TidyIcon");
/** Search. Hover: The lens is swept across the field and stops; the focus closes in and a glint crosses the glass.. Press: plays the same act. */
export const SearchIcon = /* @__PURE__ */ glyphIcon(glyphs.searchGlyph, "SearchIcon");
/** Zoom In. Hover: The lens is pushed in along its handle and the plus under it is magnified.. Press: plays the same act. */
export const ZoomInIcon = /* @__PURE__ */ glyphIcon(glyphs.zoomInGlyph, "ZoomInIcon");
/** Zoom Out. Hover: The lens is drawn back along its handle; the minus recedes and the old view closes in.. Press: plays the same act. */
export const ZoomOutIcon = /* @__PURE__ */ glyphIcon(glyphs.zoomOutGlyph, "ZoomOutIcon");
/** Fit. Hover: The content grows to the frame and the four corners clamp onto it; the open sides of the frame flash shut.. Press: plays the same act. */
export const FitIcon = /* @__PURE__ */ glyphIcon(glyphs.fitGlyph, "FitIcon");
/** Duplicate. Hover: The copy slides back onto the original, presses to take its impression, and is peeled off into place.. Press: plays the same act. */
export const DuplicateIcon = /* @__PURE__ */ glyphIcon(glyphs.duplicateGlyph, "DuplicateIcon");
/** Delete · Send away. Hover: The well turns and draws the dot round and down into its centre; it goes under with a gulp and a new dot rises on the rim.. Press: plays the same act. */
export const SendAwayIcon = /* @__PURE__ */ glyphIcon(glyphs.sendAwayGlyph, "SendAwayIcon");
/** Delete · Trash. Hover: The lid swings up on its hinge, hangs open, then falls shut; the bin gives under it and air puffs from the edge.. Press: plays the same act. */
export const TrashIcon = /* @__PURE__ */ glyphIcon(glyphs.trashGlyph, "TrashIcon");
/** Group · Stack. Hover: The two cards lift, square up into one stack and drop into the folder, splaying back into place as the flap takes the landing.. Press: plays the same act. */
export const GroupIcon = /* @__PURE__ */ glyphIcon(glyphs.groupGlyph, "GroupIcon");
/** Ungroup. Hover: The two cards are pressed together into the tray, then let go: they spring up and apart and a crack of light opens down the seam.. Press: plays the same act. */
export const UngroupIcon = /* @__PURE__ */ glyphIcon(glyphs.ungroupGlyph, "UngroupIcon");
/** Pin. Hover: The pin is drawn up rocking on its point, then driven straight down; its shadow spreads and a shock runs out along the board where it lands.. Press: plays the same act. */
export const PinIcon = /* @__PURE__ */ glyphIcon(glyphs.pinGlyph, "PinIcon");
/** Board. Hover: The ribbon is lifted and let drop; its top edge catches it, the tail runs on and springs back.. Press: plays the same act. */
export const BoardIcon = /* @__PURE__ */ glyphIcon(glyphs.boardGlyph, "BoardIcon");
/** Share · Export. Hover: The arrow crouches into the tray, pushes off and leaves; the next one rises in its place.. Press: plays the same act. */
export const ShareIcon = /* @__PURE__ */ glyphIcon(glyphs.shareGlyph, "ShareIcon");
/** Undo. Hover: The hook winds forward, whips back about its centre and reels its tail in; the head's echo carries on, a step back.. Press: plays the same act. */
export const UndoIcon = /* @__PURE__ */ glyphIcon(glyphs.undoGlyph, "UndoIcon");
/** Redo. Hover: The hook winds back, whips forward about its centre and reels its tail in; the head's echo carries on, a step on.. Press: plays the same act. */
export const RedoIcon = /* @__PURE__ */ glyphIcon(glyphs.redoGlyph, "RedoIcon");
/** More. Hover: The first dot is struck into the row; the knock runs through and kicks the last one out: there is more.. Press: plays the same act. */
export const MoreIcon = /* @__PURE__ */ glyphIcon(glyphs.moreGlyph, "MoreIcon");
/** Close. Hover: A pen crosses it out: the first stroke marks down, the second strikes through it, and the crossing takes the impact.. Press: plays the same act. */
export const CloseIcon = /* @__PURE__ */ glyphIcon(glyphs.closeGlyph, "CloseIcon");
/** Check. Hover: A pen writes the tick: down the short leg, pressed into the corner, flicked up the long leg, and the tip rings.. Press: plays the same act. */
export const CheckIcon = /* @__PURE__ */ glyphIcon(glyphs.checkGlyph, "CheckIcon");
/** Synced. Hover: The satellite winds back, laps the core once and clicks home into its slot.. Press: plays the same act. */
export const SyncedIcon = /* @__PURE__ */ glyphIcon(glyphs.syncedGlyph, "SyncedIcon");
/** Offline. Hover: The lost satellite swings back toward its slot, falls a unit short and is thrown back out.. Press: plays the same act. */
export const OfflineIcon = /* @__PURE__ */ glyphIcon(glyphs.offlineGlyph, "OfflineIcon");
/** Sync Error. Hover: The orbit heaves to turn, catches on a stop and rattles against it; the mark jolts.. Press: plays the same act. */
export const SyncErrorIcon = /* @__PURE__ */ glyphIcon(glyphs.syncErrorGlyph, "SyncErrorIcon");
/** Capture. Hover: The corners close in and hunt for focus, lock, and the shutter blinks over the aperture.. Press: plays the same act. */
export const CaptureIcon = /* @__PURE__ */ glyphIcon(glyphs.captureGlyph, "CaptureIcon");
/** Paste. Hover: The clip levers open, the content drops onto the board, and the clip clamps it down.. Press: plays the same act. */
export const PasteIcon = /* @__PURE__ */ glyphIcon(glyphs.pasteGlyph, "PasteIcon");
/** Keeper. Hover: The character looks up at it, perks up, and nods it in with a slow blink; its ring tips with the nod.. Press: plays the same act. */
export const KeeperIcon = /* @__PURE__ */ glyphIcon(glyphs.keeperGlyph, "KeeperIcon");
/** New. Hover: The upright is lifted and driven into the waiting crossbar; the knock runs out to the bar's ends.. Press: plays the same act. */
export const PlusIcon = /* @__PURE__ */ glyphIcon(glyphs.plusGlyph, "PlusIcon");
/** Remove · Less. Hover: The bar is pried up off its tile, as if one were taken from it, and set back down; the tile takes its weight.. Press: plays the same act. */
export const MinusIcon = /* @__PURE__ */ glyphIcon(glyphs.minusGlyph, "MinusIcon");
/** Chevron · Open. Hover: The chevron is drawn back and thrust the way it points; its arms fold in behind the point like a hinge, and an echo carries on.. Press: plays the same act. */
export const ChevronIcon = /* @__PURE__ */ glyphIcon(glyphs.chevronGlyph, "ChevronIcon");
/** Region. Hover: The frame is set down on the canvas, and its name writes into the head behind a caret.. Press: plays the same act. */
export const RegionIcon = /* @__PURE__ */ glyphIcon(glyphs.regionGlyph, "RegionIcon");
/** Task. Hover: The box is pressed down; while it is held the tick is written, and released it springs back up with a click.. Press: plays the same act. */
export const TaskIcon = /* @__PURE__ */ glyphIcon(glyphs.taskGlyph, "TaskIcon");
/** Tag. Hover: The cord tugs the tag by its eyelet, and it swings there and comes to hang still.. Press: plays the same act. */
export const TagIcon = /* @__PURE__ */ glyphIcon(glyphs.tagGlyph, "TagIcon");
/** Calendar. Hover: Today's leaf curls up and flips over the binding, kicking the rings, and a fresh page is left.. Press: plays the same act. */
export const CalendarIcon = /* @__PURE__ */ glyphIcon(glyphs.calendarGlyph, "CalendarIcon");
/** Document. Hover: A thumb folds the corner down, the page turns, and the next page's lines write in.. Press: plays the same act. */
export const DocumentIcon = /* @__PURE__ */ glyphIcon(glyphs.documentGlyph, "DocumentIcon");
/** Time. Hover: An hour passes: the minute hand sweeps round as the hour hand steps one on, a tick marks the hour, and the hands are set back.. Press: plays the same act. */
export const ClockIcon = /* @__PURE__ */ glyphIcon(glyphs.clockGlyph, "ClockIcon");
/** Me. Hover: Today's point runs back along your days and climbs to today again, drawing the trend behind it.. Press: plays the same act. */
export const MeIcon = /* @__PURE__ */ glyphIcon(glyphs.meGlyph, "MeIcon");
/** Seed sample. Hover: The seed is dropped in and lands on its bottom; the sprout takes the blow, springs up, and its leaf swings.. Press: plays the same act. */
export const SeedIcon = /* @__PURE__ */ glyphIcon(glyphs.seedGlyph, "SeedIcon");
/** Send. Hover: The arrow crouches on the disc, pushes off its floor and launches; the floor springs back.. Press: plays the same act. */
export const SendIcon = /* @__PURE__ */ glyphIcon(glyphs.sendGlyph, "SendIcon");
/** Stop. Hover: The block is lifted and set down hard in the middle of the key; everything closes in on it and stops.. Press: plays the same act. */
export const StopIcon = /* @__PURE__ */ glyphIcon(glyphs.stopGlyph, "StopIcon");
/** Attach. Hover: The clip is drawn back and slid onto a sheet; the sheet's edge shows under it as it bites.. Press: plays the same act. */
export const AttachIcon = /* @__PURE__ */ glyphIcon(glyphs.attachGlyph, "AttachIcon");
/** Retry · Try again. Hover: The arrowhead backs up round the loop, erasing it, and goes again, drawing it.. Press: plays the same act. */
export const RetryIcon = /* @__PURE__ */ glyphIcon(glyphs.retryGlyph, "RetryIcon");
/** Save. Hover: The disk is pushed home; as it seats the shutter catches and slides open, then springs shut.. Press: plays the same act. */
export const SaveIcon = /* @__PURE__ */ glyphIcon(glyphs.saveGlyph, "SaveIcon");
/** Download. Hover: The arrow is drawn up and comes down onto the floor, which takes it.. Press: plays the same act. */
export const DownloadIcon = /* @__PURE__ */ glyphIcon(glyphs.downloadGlyph, "DownloadIcon");
/** Upload. Hover: The arrow crouches and pushes up to the ceiling, which takes it.. Press: plays the same act. */
export const UploadIcon = /* @__PURE__ */ glyphIcon(glyphs.uploadGlyph, "UploadIcon");
/** Person · Assign. Hover: The figure looks up and nods; its shoulders follow, and a ring opens round its head.. Press: plays the same act. */
export const PersonIcon = /* @__PURE__ */ glyphIcon(glyphs.personGlyph, "PersonIcon");
/** Notifications. Hover: The bell swings on its loop and the clapper, lagging, strikes the rim on each side.. Press: plays the same act. */
export const BellIcon = /* @__PURE__ */ glyphIcon(glyphs.bellGlyph, "BellIcon");
/** Appearance. Hover: The palette is lifted on its thumb and each paint is dabbed in turn.. Press: plays the same act. */
export const PaletteIcon = /* @__PURE__ */ glyphIcon(glyphs.paletteGlyph, "PaletteIcon");
/** Copy. Hover: The copy is laid back on the original and pressed; a light passes down it and it is pulled off into place.. Press: plays the same act. */
export const CopyIcon = /* @__PURE__ */ glyphIcon(glyphs.copyGlyph, "CopyIcon");
/** Good · Feedback. Hover: The thumb is cocked over the fist, then flicked back up past upright and stands; the fist lets go of it.. Press: plays the same act. */
export const ThumbIcon = /* @__PURE__ */ glyphIcon(glyphs.thumbGlyph, "ThumbIcon");
/** Open elsewhere · External. Hover: The arrow is drawn back into the frame and thrown out of its open corner; the frame gives behind it.. Press: plays the same act. */
export const ExternalIcon = /* @__PURE__ */ glyphIcon(glyphs.externalGlyph, "ExternalIcon");
/** Settings. Hover: The gear is wound back and turned forward a notch against a detent, clicks, and springs back home.. Press: plays the same act. */
export const SettingsIcon = /* @__PURE__ */ glyphIcon(glyphs.settingsGlyph, "SettingsIcon");
/** Filter. Hover: The funnel is shaken down once; the drop in its bowl is tossed up and falls back in.. Press: plays the same act. */
export const FilterIcon = /* @__PURE__ */ glyphIcon(glyphs.filterGlyph, "FilterIcon");
/** Sort. Hover: The up arrow is pushed up and the down arrow answers, pushed down: they pass like rows changing places.. Press: plays the same act. */
export const SortIcon = /* @__PURE__ */ glyphIcon(glyphs.sortGlyph, "SortIcon");
/** Show. Hover: The eye looks one way, then the other, and blinks; it opens wide and rays open over it.. Press: plays the same act. */
export const EyeIcon = /* @__PURE__ */ glyphIcon(glyphs.eyeGlyph, "EyeIcon");
/** Hide. Hover: The bar is drawn back and slid home across the eye; the eye shuts behind it and opens again.. Press: plays the same act. */
export const EyeOffIcon = /* @__PURE__ */ glyphIcon(glyphs.eyeOffGlyph, "EyeOffIcon");
/** Lock · Locked. Hover: The shackle is lifted and pushed home into the case, which takes it, and it clicks shut.. Press: plays the same act. */
export const LockIcon = /* @__PURE__ */ glyphIcon(glyphs.lockGlyph, "LockIcon");
/** Info · Note. Hover: The stem crouches and springs up, throwing its dot; ticks open at the top of the throw and the dot lands back on its seat.. Press: plays the same act. */
export const InfoIcon = /* @__PURE__ */ glyphIcon(glyphs.infoGlyph, "InfoIcon");
/** Warning · Urgent. Hover: The mark is lifted and struck down into the sign, which takes the blow; alarm lines open off its sides.. Press: plays the same act. */
export const WarningIcon = /* @__PURE__ */ glyphIcon(glyphs.warningGlyph, "WarningIcon");
/** Money · Coin. Hover: The coin is flipped: tossed up, turned edge-on at the top, and it lands on its edge with a clink.. Press: plays the same act. */
export const CoinIcon = /* @__PURE__ */ glyphIcon(glyphs.coinGlyph, "CoinIcon");
/** Light · Day. Hover: The disc gathers itself and swells back, flaring its rays out; they come home.. Press: plays the same act. */
export const SunIcon = /* @__PURE__ */ glyphIcon(glyphs.sunGlyph, "SunIcon");
/** Dark · Night. Hover: The crescent is tipped back and rocks home like a cradle; its star brightens and a second one twinkles out.. Press: plays the same act. */
export const MoonIcon = /* @__PURE__ */ glyphIcon(glyphs.moonGlyph, "MoonIcon");
/** Folder. Hover: The front is tipped open about its hinge, a page showing inside, and drops shut; the back takes it.. Press: plays the same act. */
export const FolderIcon = /* @__PURE__ */ glyphIcon(glyphs.folderGlyph, "FolderIcon");
/** Folder open. Hover: A page is lifted out of the open folder, the front tipping further to let it out, and put back.. Press: plays the same act. */
export const FolderOpenIcon = /* @__PURE__ */ glyphIcon(glyphs.folderOpenGlyph, "FolderOpenIcon");
/** Sidebar. Hover: The rail's edge is slid shut over its rows and springs back open; the rows come back behind it.. Press: plays the same act. */
export const SidebarIcon = /* @__PURE__ */ glyphIcon(glyphs.sidebarGlyph, "SidebarIcon");
