// Generated by scripts/build-icons.mjs from icons/src/acts/check.mjs. Do not edit.
// The check glyph's tick on the 24 grid, in the order the pen draws it: the short leg's start,
// the corner, the long leg's tip.
export const TICK = { start: { x: 5.4, y: 12.6 }, corner: { x: 9.5, y: 16.7 }, tip: { x: 18.6, y: 7.3 } } as const;
