// Generated by scripts/build-agent-docs.mjs from packages/metalui/src/components/widget/spec.ts. Do not edit.

/// The widget spec as MetalWidget reads it: the limits, and each node's props with their kinds.
enum MetalWidgetSpec {
    struct Prop: Sendable {
        enum Kind: Sendable { case string, name, number, boolean, choice, url, date, action, nodes, options, pairs }
        let kind: Kind
        let required: Bool
        let min: Double?
        let max: Double?
        /// An enum's values, or the node types a `nodes` prop takes (empty: any node that isn't nested).
        let values: [String]
    }

    static let depth = 8
    static let nodes = 200
    static let text = 4000
    static let items = 100
    static let payload = 8192
    /// URLs that pass (case-insensitive), and a field's name, as regular expressions.
    static let url = #"^(https?:|mailto:)"#
    static let name = #"^[\w.-]{1,64}$"#
    static let nested: Set<String> = ["ListItem"]

    static let props: [String: [(String, Prop)]] = [
        "Card": [
            ("title", .init(kind: .string, required: true, min: nil, max: 200, values: [])),
            ("href", .init(kind: .url, required: false, min: nil, max: nil, values: [])),
            ("description", .init(kind: .string, required: false, min: nil, max: 600, values: [])),
            ("status", .init(kind: .choice, required: false, min: nil, max: nil, values: ["live", "waiting", "failed"])),
            ("size", .init(kind: .choice, required: false, min: nil, max: nil, values: ["regular", "compact"])),
            ("children", .init(kind: .nodes, required: false, min: nil, max: nil, values: [])),
            ("footer", .init(kind: .nodes, required: false, min: nil, max: nil, values: ["Button"])),
        ],
        "List": [
            ("label", .init(kind: .string, required: false, min: nil, max: 120, values: [])),
            ("children", .init(kind: .nodes, required: true, min: nil, max: nil, values: ["ListItem"])),
        ],
        "ListItem": [
            ("text", .init(kind: .string, required: true, min: nil, max: 200, values: [])),
            ("detail", .init(kind: .string, required: false, min: nil, max: 400, values: [])),
            ("badge", .init(kind: .string, required: false, min: nil, max: 40, values: [])),
            ("action", .init(kind: .action, required: false, min: nil, max: nil, values: [])),
        ],
        "Badge": [
            ("text", .init(kind: .string, required: true, min: nil, max: 40, values: [])),
            ("led", .init(kind: .choice, required: false, min: nil, max: nil, values: ["live", "waiting", "failed", "off"])),
            ("size", .init(kind: .choice, required: false, min: nil, max: nil, values: ["regular", "compact"])),
        ],
        "Button": [
            ("label", .init(kind: .string, required: true, min: nil, max: 60, values: [])),
            ("action", .init(kind: .action, required: true, min: nil, max: nil, values: [])),
            ("cap", .init(kind: .choice, required: false, min: nil, max: nil, values: ["standard", "primary", "destructive"])),
            ("size", .init(kind: .choice, required: false, min: nil, max: nil, values: ["default", "compact"])),
            ("disabled", .init(kind: .boolean, required: false, min: nil, max: nil, values: [])),
        ],
        "Field": [
            ("name", .init(kind: .name, required: true, min: nil, max: nil, values: [])),
            ("label", .init(kind: .string, required: false, min: nil, max: 120, values: [])),
            ("input", .init(kind: .choice, required: false, min: nil, max: nil, values: ["text", "email", "number", "url"])),
            ("placeholder", .init(kind: .string, required: false, min: nil, max: 120, values: [])),
            ("defaultValue", .init(kind: .string, required: false, min: nil, max: 400, values: [])),
            ("size", .init(kind: .choice, required: false, min: nil, max: nil, values: ["large", "regular", "compact"])),
        ],
        "Select": [
            ("name", .init(kind: .name, required: true, min: nil, max: nil, values: [])),
            ("label", .init(kind: .string, required: false, min: nil, max: 120, values: [])),
            ("options", .init(kind: .options, required: true, min: nil, max: nil, values: [])),
            ("placeholder", .init(kind: .string, required: false, min: nil, max: 120, values: [])),
            ("defaultValue", .init(kind: .string, required: false, min: nil, max: 200, values: [])),
            ("size", .init(kind: .choice, required: false, min: nil, max: nil, values: ["regular", "compact"])),
        ],
        "DatePicker": [
            ("name", .init(kind: .name, required: true, min: nil, max: nil, values: [])),
            ("label", .init(kind: .string, required: false, min: nil, max: 120, values: [])),
            ("defaultValue", .init(kind: .date, required: false, min: nil, max: nil, values: [])),
            ("min", .init(kind: .date, required: false, min: nil, max: nil, values: [])),
            ("max", .init(kind: .date, required: false, min: nil, max: nil, values: [])),
            ("size", .init(kind: .choice, required: false, min: nil, max: nil, values: ["regular", "compact"])),
        ],
        "Properties": [
            ("items", .init(kind: .pairs, required: true, min: nil, max: nil, values: [])),
            ("size", .init(kind: .choice, required: false, min: nil, max: nil, values: ["regular", "compact"])),
        ],
        "Markdown": [
            ("text", .init(kind: .string, required: true, min: nil, max: nil, values: [])),
        ],
        "Progress": [
            ("label", .init(kind: .string, required: false, min: nil, max: 120, values: [])),
            ("value", .init(kind: .number, required: false, min: 0, max: 100, values: [])),
            ("state", .init(kind: .choice, required: false, min: nil, max: nil, values: ["running", "paused", "failed", "complete"])),
        ],
        "Meter": [
            ("label", .init(kind: .string, required: true, min: nil, max: 120, values: [])),
            ("value", .init(kind: .number, required: true, min: nil, max: nil, values: [])),
            ("min", .init(kind: .number, required: false, min: nil, max: nil, values: [])),
            ("max", .init(kind: .number, required: false, min: nil, max: nil, values: [])),
        ],
        "Alert": [
            ("kind", .init(kind: .choice, required: false, min: nil, max: nil, values: ["note", "done", "waiting", "urgent", "failed"])),
            ("title", .init(kind: .string, required: true, min: nil, max: 200, values: [])),
            ("description", .init(kind: .string, required: false, min: nil, max: 600, values: [])),
            ("actions", .init(kind: .nodes, required: false, min: nil, max: nil, values: ["Button"])),
        ],
    ]
}
