// icons/src/icons.mjs → morph geometry (packages/metalui/src/icons/morph.generated.ts).
// The reading of a glyph into wires, beads, plates and depth relations is scripts/lib/morph-parts.mjs.
import { ICONS } from '../packages/metalui/icons/src/icons.mjs';
import { emit, finish } from './lib/emit.mjs';
import { glyphParts, isMorphable } from './lib/morph-parts.mjs';

const row = (r) => `    [${JSON.stringify(r[0])}, ${r[1]}, ${r[2]}, ${r[3]}, ${r[4]}${r[5] ? `, ${JSON.stringify(r[5])}` : ''}]`;
const glyphs = ICONS.map((ic) => [ic.name, glyphParts(ic)]);
const family = glyphs.filter(([, r]) => isMorphable(r));
// One const per glyph, so a morph between known glyphs ships only their parts (MorphPair).
const pascal = (n) => n.split('-').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
const morphConst = (name) => `${pascal(name)[0].toLowerCase()}${pascal(name).slice(1)}Morph`;
const rows = family.map(([name, r]) => `export const ${morphConst(name)}: readonly MorphPartSource[] = [\n${r.map(row).join(',\n').replace(/^  /gm, '')},\n];`);
const names = family.map(([name]) => JSON.stringify(name));
emit('packages/metalui/src/icons/morph.generated.ts', `// Generated by scripts/build-morph.mjs from icons/src/icons.mjs. Do not edit.
// Each glyph at rest as morphable parts: [path, weight, tint, solid, opacity, relations?].
//   path      one wire (open, or closed with Z), a bead (a lone point), or a plate (outer + holes)
//   weight    wire width in 24u; a bead's diameter; 0 for a plate
//   tint      duotone fill opacity (scaled by the colorway's --mu-duo-k); solid is 1 for solid fills
//   relations depth. ["behind", part, r]: hidden within that part's ink widened by r.
//             ["inside", part, r]: visible only within that part's body narrowed by r.
// Glyphs with a solid plate (characters, mascots) are not in the morph family (docs/ICON-GRAMMAR.md, K0).

export type MorphRelationSource = readonly [kind: 'behind' | 'inside', part: number, r: number];
export type MorphPartSource = readonly [path: string, weight: number, tint: number, solid: number, opacity: number, relations?: readonly MorphRelationSource[]];

/** The icons that morph: every wire-based glyph of the set. */
export const MORPH_NAMES = [${names.join(', ')}] as const;
export type MorphIconName = (typeof MORPH_NAMES)[number];

${rows.join('\n\n')}

/** Every glyph of the family by name, for MorphIcon. Importing it ships every glyph's parts. */
export const MORPH_PARTS: Record<MorphIconName, readonly MorphPartSource[]> = {
${family.map(([name]) => `  ${JSON.stringify(name)}: ${morphConst(name)},`).join('\n')}
};
`);
finish(`morph geometry (${family.length} of ${ICONS.length})`);
